### ISSUE TITLE
Code Editor Display Error

### ISSUE THREAD

**Issue by stelehm** [jcrodriguez-dis/moodle-mod_vpl#36] opened 2016-12-05 15:17 UTC
Since updating to the new version of VPL (3.2), some students are complaining that they are unable to see the Code Editor. Some strange display errors occur, showing only one half of the editor or scrambling the elements . This seems to be depending on the used browser-version.
It furthermore does not show up on every single vpl-actitivy, but only a selected few. But it does show up constantly within these actitivies.
I currently do not have any more information on this issue, but wanted to let you know anyway.

**Comment by jcrodriguez-dis** [comment] 2016-12-05 16:05
Thank stelehm for your report,
please, keep me informed about what your students say about the use of VPL 3.2. Notice that if you have updated (not fresh install) it is good idea to "Purge all caches" in your server. Also, if you can, ask about the browser version used.

Best regards
Juan Carlos.

**Comment by tbutsch** [comment] 2016-12-10 11:03
Hi there,
  I can confirm this error. I use Moodle 3.2+ (Build: 20161208) with the Boost-theme and Virtual programming lab 3.2.1 (2016120812). I use the newest Version of Chrome / Firefox an Internet Explorer. My Students and I do not see the editor. We like the VPL so much, but with the new update the editor disappeared.
![unbenannt](https://cloud.githubusercontent.com/assets/24491734/21072883/810dd60a-bed0-11e6-9f12-28471c684f21.PNG)
Please help.
Best regards
Thorsten Butsch

**Comment by jcrodriguez-dis** [comment] 2016-12-11 11:23
Hello butsch and stelehm,
This is an annoying issue due to its effects and because I can't reproduce it. After studying the possible reasons that can generate this, I guess that may be some conflict with the use of JQuery. I have changed VPL to use only the JQuery in VPL and don't try to use the Moodle one.

Please, test this
https://github.com/jcrodriguez-dis/moodle-mod_vpl/tree/v3.2.2
or replace this file in VPL 3.2.1
https://github.com/jcrodriguez-dis/moodle-mod_vpl/blob/v3.2.2/editor/editor_utility.php

Please, tell us if this resolve or not the problem.

Best regards,
Juan Carlos

**Comment by tbutsch** [comment] 2016-12-11 11:33
Hiphip huray!

Problem solved! The editor is working fine!

Thank's a lot!

Best regards,

Thorsten Butsch


Am 11.12.2016 um 12:23 schrieb jcrodriguez-dis:

**Comment by jcrodriguez-dis** [comment] 2016-12-11 19:37
Resolved in VPL3.2.2

**Closed by jcrodriguez-dis** 2016-12-11 19:37 UTC
