### ISSUE TITLE
Malformed Evaluate Request

### ISSUE THREAD

**Issue by guimota** [jcrodriguez-dis/moodle-mod_vpl#12] opened 2015-09-24 00:43 UTC
Dear VPL Developpers,

Here at Rio de Janeiro University moodle environment, we noticed a strange behaviour of VPL module after updating to the new version (that one which doesn't need java!!!). 

The first weird thing that happened was that some old assignments automatic evaluation still worked well while others didn't. After investigating in depth the problem, we believe we have understood the differences between tasks that still work well and not.  
    
Assignments with only one test case seems to be generating invalid or fail in sending the evaluation request to the jail system. Assignments with two or more tests cases are all working well. So, we 've just duplicated the single test cases and the assignment turned out to work pretty we.   

Please, verify if the same error occurs elsewhere. We would be glad to know if it is a drawback of the moodle installation at Rio de Janeiro State University.

Thank you very much, we consider VPL extremely useful for teaching programming languages.

Regards,
Guilherme Lucio Abelha Mota
Associate Professor at Rio de Janeiro State University

**Comment by jcrodriguez-dis** [comment] 2015-09-24 03:20
Hello Guilherme,
thanks for your bug report.
I have tried to reproduce the problem, but I don't have succeeded.
To better spot the problem, I need the "test cases" definition file and the program that don't pass the test.

Best regards.
Juan Carlos Rodríguez

**Comment by guimota** [comment] 2015-09-24 17:08
Holla, Juan,

Test case that don't produce an evaluation, It seams that the evaluation
process is not accomplished.

*Bad test case:*

case=teste 1
output=-10.00    14.00
 0.00    32.00
10.00    50.00
20.00    68.00
30.00    86.00
40.00    104.00
50.00    122.00
grade reduction=100%



*test case that work well:*
case=teste 1
output=-10.00    14.00
 0.00    32.00
10.00    50.00
20.00    68.00
30.00    86.00
40.00    104.00
50.00    122.00
grade reduction=50%
case=teste 2
output=-10.00    14.00
 0.00    32.00
10.00    50.00
20.00    68.00
30.00    86.00
40.00    104.00
50.00    122.00
grade reduction=50%

*Test program:*

#include <stdio.h>
#define LOWER -10.0
#define UPPER 50.0
#define STEP 10.0

float Cels2Fahr(float);

int main()
{
    float celsius;
    for (celsius = LOWER; celsius <= UPPER; celsius+=STEP)
        printf("%5.2f\t%5.2f\n", celsius, Cels2Fahr(celsius));
    return 0;
}

float Cels2Fahr(float celsius)
{
    return celsius * 9.0 / 5.0 + 32.0;
}



Attached Malfunction.png and WorkingWell.png are the respective results
screenshots.

Gracias,
Guilherme




Guilherme Lucio Abelha Mota, Dr.
Professor Adjunto
Departamento de Informática e Ciência da Computação
Universidade do Estado do Rio de Janeiro

--
Guilherme Lucio Abelha Mota, D.Sc.
Associate Professor
Department of Informatics and Computer Science
Rio de Janeiro State University

--

2015-09-24 0:20 GMT-03:00 jcrodriguez-dis <notifications@github.com>:

**Comment by jcrodriguez-dis** [comment] 2015-09-24 18:57
I don't see any attached screenshots.
I have tested the cases and the code, on the demovpl site, but the two seem working correctly. Please, test it your self.
There seems to be another unknown elements that is interfering.
What version of VPL are you using?
Please, if you can, send me, by e-mail, the problematic activity, in a backup format, to reproduce the problem with more reliability.
Best regards
Juan Carlos

**Comment by guimota** [comment] 2015-09-24 21:08
Holla, Juan,

Images were attached in last email. Do you have another address to which I
can send the screen shots?

Tomorow I send you the remaining information.

Regards,
Guilherme

On Thursday, September 24, 2015, jcrodriguez-dis <notifications@github.com>
wrote:

> I don't see any attached screenshots.
> I have tested the cases and the code, on the demovpl site, but the two
> seem working correctly. Please, test it your self.
> There seems to be another unknown elements that is interfering.
> What version of VPL are you using?
> Please, if you can, send me, by e-mail, the problematic activity, in a
> backup format, to reproduce the problem with more reliability.
> Best regards
> Juan Carlos
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcrodriguez-dis/moodle-mod_vpl/issues/12#issuecomment-143019209>
> .
>


-- 

Guilherme Lucio Abelha Mota, Dr.
Professor Adjunto
Departamento de Informática e Ciência da Computação
Universidade do Estado do Rio de Janeiro

--
Guilherme Lucio Abelha Mota, D.Sc.
Associate Professor
Department of Informatics and Computer Science
Rio de Janeiro State University

--

**Comment by jcrodriguez-dis** [comment] 2015-09-24 23:54
It seems that github has removed the images attached.
You can send and e-mail to jcrodriguez---##---dis.ulpgc.es
Of course, you must replace ---##--- by @
Best regards
Juan Carlos

**Comment by jcrodriguez-dis** [comment] 2015-09-25 00:33
Now I can see the problem.
I see that you are using VPL 3.1 , I think that this problem was fixed in VPL 3.1.2
You also can patch your  VPL 3.1, by replacing your /mod/vpl/jail/default_scripts/default_evaluate.sh by the one at 3.1.2 or higher
see
https://github.com/jcrodriguez-dis/moodle-mod_vpl/commit/46305889e981a073737e53c34a14428783b09ddc

Please, confirm that this resolve your problem.

Best regards.

**Closed** 2016-09-21 14:59 UTC
